spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jwt_todo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  redis:
    host: localhost
    port: 6379

jwt:
  security:
    key: gaonnurijwttesttesttest